export const GET_PRODUCT = "GET_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const ADD_OR_REMOVE_FROM_WISHLIST = "ADD_OR_REMOVE_FROM_WISHLIST";
export const ADD_OR_REMOVE_FROM_CART = "ADD_OR_REMOVE_FROM_CART";
export const CLEAR_SEARCH_PRODUCT = "CLEAR_SEARCH_PRODUCT";
export const SEARCH_PRODUCT_ERROR = "SEARCH_PRODUCT_ERROR";
